name: CI/CD

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Site Assets Cache
        uses: actions/cache@v2
        with:
          path: assets/resized
          key: ${{ runner.os }}-v2-site-${{ hashFiles('assets/**') }}
          restore-keys: |
            ${{ runner.os }}-v2-site-
      - name: Prep site
        run: |
          touch resume/AlexSaveau.pdf
          echo "url: http://localhost:4000" >> _config.yml
          .build/build_site.sh
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
      - name: Validate HTML
        run: |
          bundle exec jekyll serve --no-watch --detach --skip-initial-build
          bundle exec htmlproofer --assume-extension \
            --check-html --check-favicon --check-opengraph \
            --report-eof-tags --report-mismatched-tags --report-invalid-tags --report-missing-names \
            --file-ignore ./build/google1cff0bc53ad1c64c.html \
            --url-ignore "https://developer.android.com/studio/releases/gradle-plugin" \
            --typhoeus-config '{"headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4356.6 Safari/537.36"}}' \
            ./build
      - name: Upload site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: build/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .build/package-lock.json
      - name: Prep
        run: |
          cd .build && npm ci
      - name: Run tests
        run: |
          cd .build && npm test

  perf:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .build/package-lock.json
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Download site
        uses: actions/download-artifact@v2
        with:
          name: site
          path: build/
      - name: Prep
        run: |
          (cd .build && npm ci)
      - name: Run Lighthouse
        run: |
          bundle exec jekyll serve --no-watch --detach --skip-initial-build
          ./.build/node_modules/.bin/lhci --config=.build/lighthouserc.js autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
