name: Deploy site

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow --progress
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Site Assets Cache
        uses: actions/cache@v2
        with:
          path: assets/resized
          key: ${{ runner.os }}-v2-site-${{ hashFiles('assets/**') }}
          restore-keys: |
            ${{ runner.os }}-v2-site-
      - name: Generate resume
        run: |
          curl -L --fail --output resume/AlexSaveau.pdf \
            --url https://docs.google.com/document/d/11sHvpwRaWoafEr2k8w5uXaJB0_VuMCtSxQNsErnpet0/export?format=pdf
      - name: Hack timestamps
        run: |
          # The jekyll-last-modified-at plugin uses Git history to determine when stuff has been
          # updated. This works fine for blog posts, but not for fully templated pages that change
          # when other pages change.
          echo >> index.md
          echo >> blog/index.md
          git -c "user.name=Hacker" -c "user.email=boo@hack.com" commit -am "Timestamp hack"
      - name: Build and deploy preview
        if: github.ref != 'refs/heads/master'
        run: .build/deploy_preview_site.sh
        env:
          BUILD_ID: ${{ github.run_id }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
      - name: Build and deploy
        if: github.ref == 'refs/heads/master'
        run: .build/deploy_site.sh
        env:
          JEKYLL_PAT: ${{ secrets.USER_TOKEN }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
