name: Deploy site

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch history
        run: git fetch --prune --unshallow --progress
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Site Assets Cache
        uses: actions/cache@v3
        with:
          path: assets/resized
          key: ${{ runner.os }}-v2-site-${{ hashFiles('assets/**') }}
          restore-keys: |
            ${{ runner.os }}-v2-site-
      - name: Build and deploy preview
        if: github.ref != 'refs/heads/master'
        run: .build/deploy_preview_site.sh
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
      - name: Build and deploy
        if: github.ref == 'refs/heads/master'
        run: .build/deploy_site.sh
        env:
          JEKYLL_PAT: ${{ secrets.USER_TOKEN }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
