name: Pages Build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow --progress
      - name: Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Generate resume
        run: |
          curl --fail --output resume/AlexSaveau.pdf \
            --url https://docs.google.com/document/d/11sHvpwRaWoafEr2k8w5uXaJB0_VuMCtSxQNsErnpet0/export?format=pdf
      - name: Hack timestamps
        run: |
          # The jekyll-last-modified-at plugin uses Git history to determine when stuff has been
          # updated. This works fine for blog posts, but not for fully templated pages that change
          # when other pages change.
          echo >> index.md
          echo >> blog/index.md
          git -c "user.name=Hacker" -c "user.email=boo@hack.com" commit -am "Timestamp hack"
      - name: Build and deploy
        uses: helaili/jekyll-action@2.0.2
        env:
          JEKYLL_PAT: ${{ secrets.USER_TOKEN }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
