name: Pages Build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.2
        env:
          JEKYLL_PAT: ${{ secrets.USER_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
